version: '3.8'

services:
  postgres:
    image: postgres:9.6.21-alpine
    container_name: postgres
    logging:
      driver: none
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'psql postgres://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@localhost:5432/$${POSTGRES_DB} || exit 1'
        ]
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - 'postgres:/var/lib/postgres/data'
    networks:
      - ultra
    restart: always
  redis:
    image: redis:alpine3.13
    container_name: redis
    ports:
      - '6379:6379'
    logging:
      driver: none
    networks:
      - ultra
    volumes:
      - 'redis:/var/lib/redis/data'
    restart: always
networks:
  ultra:
    driver: bridge
volumes:
  postgres:
    driver: local
  redis:
    driver: local